Cc pwr thres
ASFHyP3/hyp3-gamma pull request #335
Opened 2021-12-11 01:33 UTC by cirrusasf

2022-02-01 22:55 UTC, jhkennedy requested changes
I really can't tell what's all going on in this PR. From what I can tell, I think the only change we're trying to make is to this command:
```
execute(f"rascc_mask {ifgname}.adf.cc {mmli} {width} 1 1 0 1 1 0.10 0.20 ", uselogging=True)
```
and I was expecting `0.10` and `0.20` to be reversed.

It looks like there's a pile of unrelated changes from an point in time where the `--apply-water-mask` option was being worked on. I tried merging in `develop`, but it still contains changes related to applying the water mask -- possibly even walking back some of the desired changes there. 

I think, it'd be better to close this PR and start a new feature branch from develop, with *just* the changes related to the cc and pwr threshold

2022-02-01 22:55 UTC, jhkennedy commented on hyp3_gamma/insar/unwrapping_geocoding.py
> +
These don't seem to be used
```suggestion
```

2022-02-01 22:55 UTC, jhkennedy commented on hyp3_gamma/insar/unwrapping_geocoding.py
> +
This doesn't seem to be used
```suggestion
```

2022-02-01 22:55 UTC, jhkennedy commented on hyp3_gamma/insar/unwrapping_geocoding.py
> +
These don't seem to be used
```suggestion
```

2022-02-02 23:00 UTC, closed without merging

2022-02-02 23:01 UTC, cirrusasf commented
close the pull request. Start the new branch cc_pwr_thres_v2. work over there.